export {default as Navbar} from './Navbar/Navbar';
export {default as Footer} from './Footer/Footer';
export {default as IntroCard} from './IntroCard/IntroCard';
export {default as Form} from './Form/Form';
export {default as IntroCardIndicatorPage} from './IntroCard/IntroCardIndicatorPage';
export {default as IntroCardAboutPage} from './IntroCard/IntroCardAboutPage';
export {default as IntroCardCoursePage} from './IntroCard/IntroCardCoursePage';
export {default as IntroCardEventsPage} from './IntroCard/IntroCardEventsPage';
export {default as IntroCardCoursesPage} from './IntroCard/IntroCardCoursesPage';
export {default as Courses} from './Courses/Courses';
export {default as CourseItem} from './Courses/CourseItem';
export {default as CourseList} from './Courses/CourseList';
export {default as About} from './About/About';
export {default as Booking} from './Booking/Booking';
export {default as Testimonial} from './Testimonial/Testimonial';
export {default as Features} from './Features/Features';
export {default as Menu} from './Menu/Menu';
export {default as ProductInfo} from './ProductInfo/ProductInfo';
export {default as Banner} from './Banner/Banner';
export {default as PricingBanner} from './PricingBanner/PricingBanner'
export {default as PricingCards} from './PricingCards/PricingCards';
export {default as HIWCard} from './HIWCard/HIWCard';
export {default as ContactForm} from './ContactForm/ContactForm'
export {default as Layout} from './Layout/Layout';

